spring:
    thymeleaf:
        cache: false
    jpa:
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate:
                show_sql: true
                format_sql: true
                search:
                    lucene_version: LUCENE_4_10_4
                    default:
                        directory_provider: ram
                        